    name: crypto_app
    description: "A new Flutter project."
    publish_to: 'none' # Remove this line if you intend to publish to pub.dev

    version: 1.0.0+1

    environment:
      sdk: '>=3.10.4 <4.0.0' # Certifique-se de que o SDK está atualizado aqui também

    dependencies:
      flutter:
        sdk: flutter
      cupertino_icons: ^1.0.2
      dio: ^5.3.3
      get_it: ^7.6.4
      hive: ^2.2.3
      hive_flutter: ^1.1.0
      flutter_riverpod: ^2.4.9
      riverpod_annotation: ^2.3.3
      equatable: ^2.0.5
      dartz: ^0.10.1
      json_annotation: ^4.9.0
      fl_chart: ^1.1.1
      flutter_launcher_icons: ^0.14.4

    dev_dependencies:
      flutter_test:
        sdk: flutter
      flutter_lints: ^2.0.0
      build_runner: ^2.4.5
      json_serializable: ^6.7.1 # Já estava assim, mas verifique
      hive_generator: ^2.0.1
      riverpod_generator: ^2.3.9
      riverpod_lint: ^2.3.5
      analyzer: ^6.4.1

    flutter:
      uses-material-design: true

    assets:
    - assets/images/

    flutter_launcher_icons:
      android: "launcher_icon" 
      ios: true                
      image_path: "assets/icone_app.png"